INFO:_:[auto_follows] started at 2020-08-05 14:32:57.219401
INFO:_:[auto_reply] started at 2020-08-05 14:32:57.216671
WARNING:_:failed to create favorite to 1290303484168818688
WARNING:_:failed to create favorite to 1290325263822118913
WARNING:_:failed to create favorite to 1290564947391340552
INFO:_:keywords 銀河帝国 are sent by JJmo6626
INFO:_:processing translate 15966379786711510455
INFO:_:[auto_follows] started at 2020-08-05 14:32:59.195084
INFO:_:[auto_follows] started at 2020-08-05 14:35:51.387705
INFO:_:[auto_follows] started at 2020-08-05 14:35:56.717641
INFO:_:all:'Galactic Empire'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 4 entries
INFO:_:processing translate 15966382138171081669
INFO:_:[auto_follows] started at 2020-08-05 14:38:55.256450
INFO:_:[auto_follows] started at 2020-08-05 14:38:57.983728
INFO:_:[auto_follows] started at 2020-08-05 14:41:57.214969
INFO:_:[auto_follows] started at 2020-08-05 14:44:56.680430
INFO:_:processing translate 15966387445642409682
INFO:_:[auto_follows] started at 2020-08-05 14:47:56.611499
INFO:_:[auto_follows] started at 2020-08-05 14:50:56.971493
INFO:_:[auto_follows] started at 2020-08-05 14:53:56.282621
INFO:_:[auto_follows] started at 2020-08-05 14:56:52.827691
INFO:_:[auto_follows] started at 2020-08-05 14:59:53.878645
INFO:_:[auto_tweets] started at 2020-08-05 14:59:57.342944
INFO:_:cat:'cs.DS' AND submittedDate:[20190505 TO 20200803235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:arxiv.arxiv:Received 5 entries
INFO:_:cat:'cs.DS' AND submittedDate:[20200712 TO 20200803235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:arxiv.arxiv:Received 5 entries
INFO:_:cat:'cs.DS' AND submittedDate:[20190312 TO 20200803235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:arxiv.arxiv:Received 5 entries
INFO:_:cat:'cs.DS' AND submittedDate:[20140521 TO 20200803235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:arxiv.arxiv:Received 5 entries
INFO:_:[auto_follows] started at 2020-08-05 15:02:54.962765
INFO:_:processing translate 15966396042334979227
INFO:_:[auto_follows] started at 2020-08-05 15:05:55.220481
INFO:_:[auto_follows] started at 2020-08-05 15:05:58.032845
INFO:_:processing translate 15966399319336617670
INFO:_:processing translate 15966400003535696019
INFO:_:processing translate 15966400083634886496
INFO:_:processing translate 15966400273842230442
INFO:_:processing translate 15966400635044848076
INFO:_:processing translate 15966400896203225624
INFO:_:[auto_follows] started at 2020-08-05 15:08:58.093404
INFO:_:[auto_follows] started at 2020-08-05 15:08:59.464632
INFO:_:processing translate 15966401197063846435
INFO:_:processing translate 15966401719380934484
INFO:_:processing translate 15966402411379286420
INFO:_:[auto_follows] started at 2020-08-05 15:11:58.091720
INFO:_:processing translate 15966403023893507285
INFO:_:processing translate 15966403606363356851
INFO:_:[auto_follows] started at 2020-08-05 15:14:54.559144
INFO:_:processing translate 15966404449267900835
INFO:_:@JJmo6626 :Galactic Empire
>三次元銀河消滅モデル
arxiv.org/abs/astro-ph/0307273v2
>銀河系暗黒物質天体の質量推定のレビュー
arxiv.org/abs/astro-ph/0002363v1
>銀河系円盤とハローの共鳴トラップと移..
arxiv.org/abs/1505.04355v1
>マゼラン雲の距離について：最初の倍音..
arxiv.org/abs/astro-ph/0206102v1
INFO:_:keywords  chocolate TG are sent by phosgene_titech
INFO:_:all:' chocolate TG'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 4 entries
INFO:_:[auto_follows] started at 2020-08-05 15:17:52.622170
INFO:_:processing translate 15966405991579081612
INFO:_:processing translate 15966406915161539239
INFO:_:[auto_follows] started at 2020-08-05 15:20:52.973113
INFO:_:[auto_follows] started at 2020-08-05 15:20:54.824214
INFO:_:processing translate 15966407869486688099
INFO:_:[auto_follows] started at 2020-08-05 15:23:52.110169
INFO:_:[auto_follows] started at 2020-08-05 15:26:53.302376
INFO:_:[auto_follows] started at 2020-08-05 15:29:51.464038
INFO:_:[auto_follows] started at 2020-08-05 15:32:51.300889
INFO:_:[auto_follows] started at 2020-08-05 15:32:59.649158
INFO:_:[auto_follows] started at 2020-08-05 15:35:59.600183
INFO:_:[auto_follows] started at 2020-08-05 15:38:57.592029
INFO:_:[auto_follows] started at 2020-08-05 15:41:55.395594
INFO:_:[auto_follows] started at 2020-08-05 15:44:51.666882
INFO:_:[auto_follows] started at 2020-08-05 15:44:56.795619
INFO:_:[auto_follows] started at 2020-08-05 15:47:57.101316
INFO:_:[auto_follows] started at 2020-08-05 15:50:54.493154
INFO:_:[auto_follows] started at 2020-08-05 15:50:58.591162
INFO:_:[auto_follows] started at 2020-08-05 15:53:58.229528
INFO:_:[auto_follows] started at 2020-08-05 15:56:52.102936
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('taishi_suny',)
INFO:_:[auto_tweets] started at 2020-08-05 15:59:54.160180
INFO:_:cat:'cs.HC' AND submittedDate:[20190303 TO 20200803235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:_:[auto_follows] started at 2020-08-05 15:59:58.759475
INFO:arxiv.arxiv:Received 5 entries
INFO:_:cat:'cs.HC' AND submittedDate:[20190627 TO 20200803235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:arxiv.arxiv:Received 5 entries
INFO:_:cat:'cs.HC' AND submittedDate:[20190420 TO 20200803235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:arxiv.arxiv:Received 5 entries
INFO:_:cat:'cs.HC' AND submittedDate:[20151025 TO 20200803235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:arxiv.arxiv:Received 5 entries
INFO:_:[auto_follows] started at 2020-08-05 16:02:56.889492
INFO:_:[auto_follows] started at 2020-08-05 16:05:56.477578
INFO:_:[auto_follows] started at 2020-08-05 16:08:56.780844
INFO:_:[auto_follows] started at 2020-08-05 16:11:58.346549
INFO:_:[auto_follows] started at 2020-08-05 16:14:59.372182
INFO:_:[auto_follows] started at 2020-08-05 16:17:56.034092
INFO:_:[auto_follows] started at 2020-08-05 16:20:54.166232
INFO:_:[auto_follows] started at 2020-08-05 16:24:00.160525
INFO:_:[auto_follows] started at 2020-08-05 16:26:53.035412
INFO:_:[auto_follows] started at 2020-08-05 16:29:52.363871
INFO:_:[auto_follows] started at 2020-08-05 16:32:52.462589
INFO:_:[auto_follows] started at 2020-08-05 16:36:01.118445
INFO:_:[auto_follows] started at 2020-08-05 16:38:57.854488
INFO:_:[auto_follows] started at 2020-08-05 16:41:59.803321
INFO:_:[auto_follows] started at 2020-08-05 16:44:55.785461
INFO:_:[auto_follows] started at 2020-08-05 16:47:54.732032
INFO:_:[auto_follows] started at 2020-08-05 16:50:52.625957
INFO:_:[auto_follows] started at 2020-08-05 16:53:55.391563
INFO:_:[auto_follows] started at 2020-08-05 16:56:56.272540
INFO:_:[auto_follows] started at 2020-08-05 16:59:55.794208
INFO:_:[auto_follows] started at 2020-08-05 17:02:59.724309
INFO:_:[auto_follows] started at 2020-08-05 17:05:56.187698
INFO:_:[auto_follows] started at 2020-08-05 17:08:58.443632
INFO:_:[auto_follows] started at 2020-08-05 17:11:52.550939
INFO:_:[auto_follows] started at 2020-08-05 17:14:55.022044
INFO:_:[auto_follows] started at 2020-08-05 17:17:53.473868
INFO:_:[auto_follows] started at 2020-08-05 17:20:57.397908
INFO:_:[auto_follows] started at 2020-08-05 17:24:00.173658
INFO:_:[auto_follows] started at 2020-08-05 17:27:01.966670
INFO:_:[auto_follows] started at 2020-08-05 17:29:57.626731
INFO:_:[auto_follows] started at 2020-08-05 17:32:55.723264
INFO:_:[auto_follows] started at 2020-08-05 17:35:58.715119
INFO:_:[auto_follows] started at 2020-08-05 17:38:53.718479
INFO:_:[auto_follows] started at 2020-08-05 17:41:59.491514
INFO:_:[auto_follows] started at 2020-08-05 17:44:59.294703
INFO:_:[auto_follows] started at 2020-08-05 17:47:51.653510
INFO:_:[auto_follows] started at 2020-08-05 17:50:58.664462
INFO:_:[auto_follows] started at 2020-08-05 17:53:58.952385
INFO:_:[auto_follows] started at 2020-08-05 17:56:55.369995
INFO:_:[auto_follows] started at 2020-08-05 17:59:52.139002
INFO:_:[auto_follows] started at 2020-08-05 18:02:53.598751
INFO:_:[auto_follows] started at 2020-08-05 18:05:58.999857
INFO:_:[auto_follows] started at 2020-08-05 18:08:59.266466
INFO:_:[auto_follows] started at 2020-08-05 18:11:56.338866
INFO:_:[auto_follows] started at 2020-08-05 18:14:56.815621
INFO:_:[auto_follows] started at 2020-08-05 18:17:55.934591
INFO:_:[auto_follows] started at 2020-08-05 18:20:51.694198
INFO:_:[auto_follows] started at 2020-08-05 18:23:55.215290
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('dmoll_op33_5',)
INFO:_:[auto_follows] started at 2020-08-05 18:26:52.739962
INFO:_:[auto_follows] started at 2020-08-05 18:29:57.056186
INFO:_:[auto_follows] started at 2020-08-05 18:32:55.143907
INFO:_:[auto_follows] started at 2020-08-05 18:35:53.558348
INFO:_:[auto_follows] started at 2020-08-05 18:38:54.499369
INFO:_:[auto_follows] started at 2020-08-05 18:41:54.189388
INFO:_:[auto_follows] started at 2020-08-05 18:44:52.149000
INFO:_:[auto_follows] started at 2020-08-05 18:47:54.996787
INFO:_:[auto_follows] started at 2020-08-05 18:50:58.153130
INFO:_:[auto_follows] started at 2020-08-05 18:53:54.569995
INFO:_:[auto_follows] started at 2020-08-05 18:56:51.961902
INFO:_:[auto_follows] started at 2020-08-05 19:00:00.014394
INFO:_:[auto_follows] started at 2020-08-05 19:02:59.740309
INFO:_:[auto_follows] started at 2020-08-05 19:05:54.436224
INFO:_:[auto_follows] started at 2020-08-05 19:08:55.353208
INFO:_:[auto_follows] started at 2020-08-05 19:11:57.436265
INFO:_:[auto_follows] started at 2020-08-05 19:14:55.959747
INFO:_:[auto_follows] started at 2020-08-05 19:17:53.539039
INFO:_:[auto_follows] started at 2020-08-05 19:20:54.047606
INFO:_:[auto_follows] started at 2020-08-05 19:23:57.840772
INFO:_:[auto_follows] started at 2020-08-05 19:27:01.607245
INFO:_:[auto_follows] started at 2020-08-05 19:29:54.403985
INFO:_:[auto_follows] started at 2020-08-05 19:32:58.471467
INFO:_:[auto_follows] started at 2020-08-05 19:35:54.604742
INFO:_:[auto_follows] started at 2020-08-05 19:38:57.251039
WARNING:_:failed to translate, 0 times
WARNING:_:Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: headless chrome=84.0.4147.105)

INFO:_:[auto_follows] started at 2020-08-05 19:41:56.246846
INFO:_:[auto_follows] started at 2020-08-05 19:44:58.468139
INFO:_:[auto_follows] started at 2020-08-05 19:47:57.091756
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/PaperTranslateBot/src/DeeplDriver.py", line 145, in translate
    translated = self._translate(text, source_lang, target_lang)
  File "/home/ubuntu/PaperTranslateBot/src/DeeplDriver.py", line 128, in _translate
    self.put_source(text)
  File "/home/ubuntu/PaperTranslateBot/src/DeeplDriver.py", line 110, in put_source
    textarea.send_keys(text)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webelement.py", line 510, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webelement.py", line 672, in _execute
    return self._parent.execute(command, params)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: headless chrome=84.0.4147.105)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/PaperTranslateBot/src/DeeplDriver.py", line 37, in process
    res = self.dDriver.translate(**obj)
  File "/home/ubuntu/PaperTranslateBot/src/DeeplDriver.py", line 150, in translate
    self.initialize()
  File "/home/ubuntu/PaperTranslateBot/src/DeeplDriver.py", line 61, in initialize
    self.driver.get("https://www.deepl.com/ja/translator")
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 330, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: headless chrome=84.0.4147.105)

INFO:_:[auto_follows] started at 2020-08-05 19:50:52.507715
INFO:_:[auto_follows] started at 2020-08-05 19:53:55.217247
INFO:_:[auto_follows] started at 2020-08-05 19:56:55.416239
INFO:_:[auto_follows] started at 2020-08-05 20:00:00.140673
INFO:_:[auto_follows] started at 2020-08-05 20:02:59.794512
INFO:_:[auto_follows] started at 2020-08-05 20:05:55.102120
INFO:_:[auto_follows] started at 2020-08-05 20:08:54.118200
INFO:_:[auto_follows] started at 2020-08-05 20:12:00.167458
INFO:_:[auto_follows] started at 2020-08-05 20:14:58.580141
INFO:_:[auto_follows] started at 2020-08-05 20:17:58.148710
INFO:_:[auto_follows] started at 2020-08-05 20:20:57.905767
INFO:_:[auto_follows] started at 2020-08-05 20:23:59.077869
INFO:_:[auto_follows] started at 2020-08-05 20:26:57.480810
INFO:_:[auto_follows] started at 2020-08-05 20:29:58.076900
INFO:_:[auto_follows] started at 2020-08-05 20:32:56.252471
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-05 20:36:05.311621
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-05 20:45:08.980108
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-05 20:56:59.718744
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-05 21:09:12.696462
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-05 21:18:09.297246
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-05 21:23:57.979072
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-05 21:30:03.801765
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
INFO:_:[auto_follows] started at 2020-08-05 21:33:00.238254
INFO:_:[auto_follows] started at 2020-08-05 21:35:52.847597
INFO:_:[auto_follows] started at 2020-08-05 21:39:01.449154
INFO:_:[auto_follows] started at 2020-08-05 21:41:52.544772
INFO:_:[auto_follows] started at 2020-08-05 21:44:57.818264
INFO:_:[auto_follows] started at 2020-08-05 21:47:58.416172
INFO:_:[auto_follows] started at 2020-08-05 21:50:52.658479
INFO:_:[auto_follows] started at 2020-08-05 21:53:56.840292
INFO:_:[auto_follows] started at 2020-08-05 21:56:59.546455
INFO:_:[auto_follows] started at 2020-08-05 21:59:58.960839
INFO:_:[auto_follows] started at 2020-08-05 22:02:57.627299
INFO:_:[auto_follows] started at 2020-08-05 22:05:54.250435
INFO:_:[auto_follows] started at 2020-08-05 22:08:58.608332
INFO:_:[auto_follows] started at 2020-08-05 22:11:59.411360
INFO:_:[auto_follows] started at 2020-08-05 22:15:00.397785
INFO:_:[auto_follows] started at 2020-08-05 22:17:57.650915
INFO:_:[auto_follows] started at 2020-08-05 22:20:53.251766
INFO:_:[auto_follows] started at 2020-08-05 22:23:55.447923
INFO:_:[auto_follows] started at 2020-08-05 22:27:00.548990
INFO:_:[auto_follows] started at 2020-08-05 22:29:53.236900
INFO:_:[auto_follows] started at 2020-08-05 22:32:56.932469
INFO:_:[auto_follows] started at 2020-08-05 22:35:52.559290
INFO:_:[auto_follows] started at 2020-08-05 22:38:57.349884
INFO:_:[auto_follows] started at 2020-08-05 22:41:54.464324
INFO:_:[auto_follows] started at 2020-08-05 22:44:55.190258
INFO:_:[auto_follows] started at 2020-08-05 22:47:57.876222
INFO:_:[auto_follows] started at 2020-08-05 22:50:58.334454
INFO:_:[auto_follows] started at 2020-08-05 22:53:52.135437
INFO:_:[auto_follows] started at 2020-08-05 22:56:55.923568
INFO:_:[auto_follows] started at 2020-08-05 22:59:57.763866
INFO:_:[auto_follows] started at 2020-08-05 23:02:56.508117
INFO:_:[auto_follows] started at 2020-08-05 23:05:58.237123
INFO:_:[auto_follows] started at 2020-08-05 23:09:00.502830
INFO:_:[auto_follows] started at 2020-08-05 23:11:54.997373
INFO:_:[auto_follows] started at 2020-08-05 23:14:56.536858
INFO:_:[auto_follows] started at 2020-08-05 23:17:52.127698
INFO:_:[auto_follows] started at 2020-08-05 23:20:52.071788
INFO:_:[auto_follows] started at 2020-08-05 23:23:52.215251
INFO:_:[auto_follows] started at 2020-08-05 23:26:51.718743
INFO:_:[auto_follows] started at 2020-08-05 23:29:53.747044
INFO:_:[auto_follows] started at 2020-08-05 23:32:52.430759
INFO:_:[auto_follows] started at 2020-08-05 23:35:53.370280
INFO:_:[auto_follows] started at 2020-08-05 23:38:56.685788
INFO:_:[auto_follows] started at 2020-08-05 23:41:58.866313
INFO:_:[auto_follows] started at 2020-08-05 23:45:00.852379
INFO:_:[auto_follows] started at 2020-08-05 23:47:53.210813
INFO:_:[auto_follows] started at 2020-08-05 23:50:54.400324
INFO:_:[auto_follows] started at 2020-08-05 23:53:59.466545
INFO:_:[auto_follows] started at 2020-08-05 23:56:52.724188
INFO:_:[auto_follows] started at 2020-08-05 23:59:55.751605
INFO:_:[auto_follows] started at 2020-08-06 00:02:56.255485
INFO:_:[auto_follows] started at 2020-08-06 00:05:56.087890
INFO:_:[auto_follows] started at 2020-08-06 00:08:55.036751
INFO:_:[auto_follows] started at 2020-08-06 00:11:55.370026
INFO:_:[auto_follows] started at 2020-08-06 00:14:55.934625
INFO:_:[auto_follows] started at 2020-08-06 00:17:54.921196
INFO:_:[auto_follows] started at 2020-08-06 00:20:53.854412
INFO:_:[auto_follows] started at 2020-08-06 00:23:58.082025
INFO:_:[auto_follows] started at 2020-08-06 00:26:52.314643
INFO:_:[auto_follows] started at 2020-08-06 00:29:52.080464
INFO:_:[auto_follows] started at 2020-08-06 00:32:58.723540
INFO:_:[auto_follows] started at 2020-08-06 00:35:58.992144
INFO:_:[auto_follows] started at 2020-08-06 00:39:00.712606
INFO:_:[auto_follows] started at 2020-08-06 00:41:55.976192
INFO:_:[auto_follows] started at 2020-08-06 00:44:55.020069
INFO:_:[auto_follows] started at 2020-08-06 00:47:57.170025
INFO:_:[auto_follows] started at 2020-08-06 00:51:00.254134
INFO:_:[auto_follows] started at 2020-08-06 00:53:59.630160
INFO:_:[auto_follows] started at 2020-08-06 00:56:58.987754
INFO:_:[auto_follows] started at 2020-08-06 00:59:57.796884
INFO:_:[auto_follows] started at 2020-08-06 01:02:56.277505
INFO:_:[auto_follows] started at 2020-08-06 01:06:00.430786
INFO:_:[auto_follows] started at 2020-08-06 01:08:56.381332
INFO:_:[auto_follows] started at 2020-08-06 01:12:00.506281
INFO:_:[auto_follows] started at 2020-08-06 01:15:00.525464
INFO:_:[auto_follows] started at 2020-08-06 01:18:00.173424
INFO:_:[auto_follows] started at 2020-08-06 01:21:00.474692
INFO:_:[auto_follows] started at 2020-08-06 01:23:55.290170
INFO:_:[auto_follows] started at 2020-08-06 01:26:59.628557
INFO:_:[auto_follows] started at 2020-08-06 01:29:55.152770
INFO:_:[auto_follows] started at 2020-08-06 01:32:52.319925
INFO:_:[auto_follows] started at 2020-08-06 01:35:57.712607
INFO:_:[auto_follows] started at 2020-08-06 01:38:53.938735
INFO:_:[auto_follows] started at 2020-08-06 01:41:57.565441
INFO:_:[auto_follows] started at 2020-08-06 01:44:55.626299
INFO:_:[auto_follows] started at 2020-08-06 01:47:59.717329
INFO:_:[auto_follows] started at 2020-08-06 01:50:58.737811
INFO:_:[auto_follows] started at 2020-08-06 01:53:53.020689
INFO:_:[auto_follows] started at 2020-08-06 01:56:54.978169
INFO:_:[auto_follows] started at 2020-08-06 01:59:57.992362
INFO:_:[auto_follows] started at 2020-08-06 02:02:59.049327
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))
INFO:_:[auto_follows] started at 2020-08-06 02:05:54.173482
INFO:_:[auto_follows] started at 2020-08-06 02:08:58.778097
INFO:_:[auto_follows] started at 2020-08-06 02:11:59.146439
INFO:_:[auto_follows] started at 2020-08-06 02:14:52.927124
INFO:_:[auto_follows] started at 2020-08-06 02:17:52.811490
INFO:_:[auto_follows] started at 2020-08-06 02:20:52.080537
INFO:_:[auto_follows] started at 2020-08-06 02:23:53.910389
INFO:_:[auto_follows] started at 2020-08-06 02:26:57.207459
INFO:_:[auto_follows] started at 2020-08-06 02:29:56.786680
INFO:_:[auto_follows] started at 2020-08-06 02:32:53.404438
INFO:_:[auto_follows] started at 2020-08-06 02:36:00.043624
INFO:_:[auto_follows] started at 2020-08-06 02:38:59.791998
INFO:_:[auto_follows] started at 2020-08-06 02:41:51.538164
INFO:_:[auto_follows] started at 2020-08-06 02:44:55.695611
INFO:_:[auto_follows] started at 2020-08-06 02:47:53.912014
INFO:_:[auto_follows] started at 2020-08-06 02:50:52.502230
INFO:_:[auto_follows] started at 2020-08-06 02:53:54.843139
INFO:_:[auto_follows] started at 2020-08-06 02:56:57.528133
INFO:_:[auto_follows] started at 2020-08-06 02:59:52.000633
INFO:_:[auto_follows] started at 2020-08-06 03:03:00.102374
INFO:_:[auto_follows] started at 2020-08-06 03:05:59.678220
INFO:_:[auto_follows] started at 2020-08-06 03:09:00.188482
INFO:_:[auto_follows] started at 2020-08-06 03:11:58.988664
INFO:_:[auto_follows] started at 2020-08-06 03:14:56.221040
INFO:_:[auto_follows] started at 2020-08-06 03:18:00.709845
INFO:_:[auto_follows] started at 2020-08-06 03:21:00.255182
INFO:_:[auto_follows] started at 2020-08-06 03:23:55.950545
INFO:_:[auto_follows] started at 2020-08-06 03:26:51.890858
INFO:_:[auto_follows] started at 2020-08-06 03:29:59.051499
INFO:_:[auto_follows] started at 2020-08-06 03:32:58.374078
INFO:_:[auto_follows] started at 2020-08-06 03:35:56.400964
INFO:_:[auto_follows] started at 2020-08-06 03:38:57.356831
INFO:_:[auto_follows] started at 2020-08-06 03:42:01.135332
INFO:_:[auto_follows] started at 2020-08-06 03:44:54.559096
INFO:_:[auto_follows] started at 2020-08-06 03:47:59.801211
INFO:_:[auto_follows] started at 2020-08-06 03:50:53.707918
INFO:_:[auto_follows] started at 2020-08-06 03:53:58.563200
INFO:_:[auto_follows] started at 2020-08-06 03:56:57.794646
INFO:_:[auto_follows] started at 2020-08-06 03:59:54.612224
INFO:_:[auto_follows] started at 2020-08-06 04:02:58.057579
INFO:_:[auto_follows] started at 2020-08-06 04:05:58.554403
INFO:_:[auto_follows] started at 2020-08-06 04:08:54.244158
INFO:_:[auto_follows] started at 2020-08-06 04:11:56.378371
INFO:_:[auto_follows] started at 2020-08-06 04:14:53.181684
INFO:_:[auto_follows] started at 2020-08-06 04:17:52.083288
INFO:_:[auto_follows] started at 2020-08-06 04:20:52.515758
INFO:_:[auto_follows] started at 2020-08-06 04:23:59.057303
INFO:_:[auto_follows] started at 2020-08-06 04:27:00.479906
INFO:_:[auto_follows] started at 2020-08-06 04:29:56.471885
INFO:_:[auto_follows] started at 2020-08-06 04:32:58.224588
INFO:_:[auto_follows] started at 2020-08-06 04:35:51.995765
INFO:_:[auto_follows] started at 2020-08-06 04:38:57.355161
INFO:_:[auto_follows] started at 2020-08-06 04:41:58.740809
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('cpCACL',)
INFO:_:[auto_follows] started at 2020-08-06 04:44:57.814618
INFO:_:[auto_follows] started at 2020-08-06 04:47:59.085213
INFO:_:[auto_follows] started at 2020-08-06 04:50:53.251828
INFO:_:[auto_follows] started at 2020-08-06 04:53:57.276772
INFO:_:[auto_follows] started at 2020-08-06 04:56:52.733580
INFO:_:[auto_follows] started at 2020-08-06 04:59:59.838019
INFO:_:[auto_follows] started at 2020-08-06 05:02:52.357031
INFO:_:[auto_follows] started at 2020-08-06 05:05:57.031013
INFO:_:[auto_follows] started at 2020-08-06 05:08:53.964744
INFO:_:[auto_follows] started at 2020-08-06 05:11:59.891073
INFO:_:[auto_follows] started at 2020-08-06 05:14:58.075390
INFO:_:[auto_follows] started at 2020-08-06 05:17:58.787004
INFO:_:[auto_follows] started at 2020-08-06 05:20:53.582217
INFO:_:[auto_follows] started at 2020-08-06 05:23:56.970494
INFO:_:[auto_follows] started at 2020-08-06 05:27:00.964726
INFO:_:[auto_follows] started at 2020-08-06 05:29:58.932686
INFO:_:[auto_follows] started at 2020-08-06 05:32:59.716604
INFO:_:[auto_follows] started at 2020-08-06 05:35:53.065829
INFO:_:[auto_follows] started at 2020-08-06 05:38:57.550039
INFO:_:[auto_follows] started at 2020-08-06 05:41:52.034829
INFO:_:[auto_follows] started at 2020-08-06 05:44:59.210834
INFO:_:[auto_follows] started at 2020-08-06 05:47:54.540954
INFO:_:[auto_follows] started at 2020-08-06 05:50:57.307640
INFO:_:[auto_follows] started at 2020-08-06 05:53:53.353642
INFO:_:[auto_follows] started at 2020-08-06 05:56:52.528305
INFO:_:[auto_follows] started at 2020-08-06 05:59:58.200170
INFO:_:[auto_follows] started at 2020-08-06 06:02:58.499398
INFO:_:[auto_follows] started at 2020-08-06 06:05:55.592474
INFO:_:[auto_follows] started at 2020-08-06 06:08:56.540359
INFO:_:[auto_follows] started at 2020-08-06 06:11:54.009531
INFO:_:[auto_follows] started at 2020-08-06 06:14:55.867004
INFO:_:[auto_follows] started at 2020-08-06 06:17:54.924301
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('lobi_roots',)
INFO:_:[auto_follows] started at 2020-08-06 06:20:57.644479
INFO:_:[auto_follows] started at 2020-08-06 06:23:58.094807
INFO:_:[auto_follows] started at 2020-08-06 06:26:56.542143
INFO:_:[auto_follows] started at 2020-08-06 06:29:58.335088
INFO:_:[auto_follows] started at 2020-08-06 06:32:56.114934
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('BMinorWaltz',)
INFO:_:[auto_follows] started at 2020-08-06 06:35:54.699250
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('ArihirOoooooooO',)
INFO:_:[auto_follows] started at 2020-08-06 06:38:56.845491
INFO:_:[auto_follows] started at 2020-08-06 06:41:55.297386
INFO:_:[auto_follows] started at 2020-08-06 06:44:56.191781
INFO:_:[auto_follows] started at 2020-08-06 06:47:56.041494
INFO:_:[auto_follows] started at 2020-08-06 06:50:55.840552
INFO:_:[auto_follows] started at 2020-08-06 06:53:58.505979
INFO:_:[auto_follows] started at 2020-08-06 06:56:52.815967
INFO:_:[auto_follows] started at 2020-08-06 06:59:58.991192
INFO:_:[auto_follows] started at 2020-08-06 07:03:00.175183
INFO:_:[auto_follows] started at 2020-08-06 07:05:57.821274
INFO:_:[auto_follows] started at 2020-08-06 07:08:57.907647
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
INFO:_:[auto_follows] started at 2020-08-06 07:12:00.547237
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
INFO:_:[auto_follows] started at 2020-08-06 07:15:01.188844
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 07:17:58.274158
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 07:24:01.086164
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 07:26:59.406022
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 07:29:56.798634
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 07:32:54.765200
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
INFO:_:[auto_follows] started at 2020-08-06 07:36:00.846631
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/friends/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 07:42:02.641874
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
INFO:_:[auto_follows] started at 2020-08-06 07:44:53.996093
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/friends/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 07:47:59.587788
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 07:51:01.848551
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 07:53:54.607946
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))
INFO:_:[auto_follows] started at 2020-08-06 07:57:02.009540
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
INFO:_:[auto_follows] started at 2020-08-06 07:59:56.947549
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 08:03:01.358296
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 08:06:01.830106
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 08:08:56.863038
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/friends/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 08:14:58.297011
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 08:21:04.203517
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(32, 'EPIPE')")))
INFO:_:[auto_follows] started at 2020-08-06 08:27:08.872445
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 08:29:57.983324
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 08:32:57.334049
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 08:35:58.462406
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 08:39:00.481716
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('mujimujimujina',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('S_on_ICE',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('13_graush',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('___ajisai',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('nagityan0806',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('hanshin_mika',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('HdGA88AOImdl1',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('9nt11',)
WARNING:_:failed to create friendship with 846292516852805632
WARNING:_:failed to create friendship with 1079359802755543040
WARNING:_:failed to create friendship with 899771512374214656
WARNING:_:failed to create friendship with 390800007
WARNING:_:failed to create friendship with 3491437034
WARNING:_:failed to create friendship with 3152478770
INFO:_:[auto_follows] started at 2020-08-06 08:53:55.277269
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 08:57:01.795780
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
INFO:_:[auto_follows] started at 2020-08-06 08:59:59.547959
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 09:03:02.104201
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 09:05:56.033805
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 09:08:54.124023
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('Schiller777',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('mujimujimujina',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('dolhide',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('S_on_ICE',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('13_graush',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('___ajisai',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('hanshin_mika',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('kisi1408',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('HdGA88AOImdl1',)
WARNING:_:failed to create friendship with 3305859968
WARNING:_:failed to create friendship with 846292516852805632
WARNING:_:failed to create friendship with 1002744777824088066
WARNING:_:failed to create friendship with 1079359802755543040
WARNING:_:failed to create friendship with 899771512374214656
WARNING:_:failed to create friendship with 390800007
WARNING:_:failed to create friendship with 3491437034
WARNING:_:failed to create friendship with 196208268
WARNING:_:failed to create friendship with 3152478770
INFO:_:[auto_follows] started at 2020-08-06 09:29:56.664462
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('colt_lepakot',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('m9fs2vpd21',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('dolhide',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('mujimujimujina',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('Schiller777',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('S_on_ICE',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('13_graush',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('___ajisai',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('010_clock',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('hanshin_mika',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('kisi1408',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('HdGA88AOImdl1',)
WARNING:_:failed to create friendship with 838207118654095361
WARNING:_:failed to create friendship with 1002744777824088066
WARNING:_:failed to create friendship with 846292516852805632
WARNING:_:failed to create friendship with 3305859968
WARNING:_:failed to create friendship with 1079359802755543040
WARNING:_:failed to create friendship with 899771512374214656
WARNING:_:failed to create friendship with 390800007
WARNING:_:failed to create friendship with 2446889702
WARNING:_:failed to create friendship with 3491437034
WARNING:_:failed to create friendship with 196208268
WARNING:_:failed to create friendship with 3152478770
INFO:_:[auto_follows] started at 2020-08-06 10:24:03.713904
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 10:30:03.164532
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 10:38:58.129301
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 10:44:57.573514
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 10:54:03.023716
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 10:57:02.057341
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 10:59:53.441715
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 11:05:54.194149
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 11:12:02.262647
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 11:20:56.211781
WARNING:_:exception at auto_follows function
WARNING:_:Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
INFO:_:[auto_follows] started at 2020-08-06 11:41:53.073370
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('CorSoYuz',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('gd_w_',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('si__da_',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('DAIGODAISUKI109',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('ATTLI_Ice',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('error_tosthenes',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('kenta_yuuki',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('Tsukasa_Iob',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('pc98macintosh',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('shvfn',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('paricodayo',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    bot = EigoyurusanBot(lock, logger)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 10, in __init__
    translate = Translate(logger)
  File "/home/ubuntu/PaperTranslateBot/src/DeeplDriver.py", line 8, in __init__
    self.dDriver = DeeplDriver(logger)
  File "/home/ubuntu/PaperTranslateBot/src/DeeplDriver.py", line 48, in __init__
    self.driver = webdriver.Chrome(service=service_, options=options_)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

Exception ignored in: <function DeeplDriver.__del__ at 0x7f78647b2430>
Traceback (most recent call last):
  File "/home/ubuntu/PaperTranslateBot/src/DeeplDriver.py", line 68, in __del__
    def __del__(self): self.driver.close()
AttributeError: 'DeeplDriver' object has no attribute 'driver'
INFO:_:[auto_follows] started at 2020-08-06 17:08:56.153188
INFO:_:[auto_reply] started at 2020-08-06 17:08:56.153511
WARNING:_:failed to create favorite to 1290325263822118913
WARNING:_:failed to create favorite to 1290564947391340552
WARNING:_:failed to create favorite to 1290700018542755840
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('toka_toka10',)
INFO:_:keywords  chocolate TG are sent by phosgene_titech
INFO:_:all:' chocolate TG'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 4 entries
INFO:_:processing translate 15967337391148460844
INFO:_:processing translate 15967337461308515225
INFO:_:processing translate 15967337641489459231
INFO:_:processing translate 15967337701541353655
INFO:_:processing translate 15967337811644675258
INFO:_:processing translate 15967337871712214488
INFO:_:processing translate 15967337951802444873
INFO:_:processing translate 15967338001850592081
INFO:_:@phosgene_titech 
>不偏不党のチョコレートバーゲームのグラン..
arxiv.org/abs/1711.05035v1
>不偏不党の三角形のチョコレートバーゲーム
arxiv.org/abs/1711.04954v1
>チョコレートブルームのラマン分光
arxiv.org/abs/1612.00741v1
>チョコレートの数字
arxiv.org/abs/1509.06093v1
INFO:_:keywords lithium deposition are sent by no_gi_gu_chi
INFO:_:all:'lithium deposition'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 4 entries
INFO:_:processing translate 15967338159118454437
INFO:_:processing translate 15967338219273507272
INFO:_:processing translate 15967338319380166470
INFO:_:processing translate 15967338379448163232
INFO:_:processing translate 1596733852959114886
INFO:_:processing translate 15967338589649376057
INFO:_:processing translate 15967338689750886479
INFO:_:processing translate 15967338749809116895
INFO:_:@no_gi_gu_chi 
>金属リチウムのEPRイメージング
arxiv.org/abs/1802.00025v1
>液体・ナノポーラス固体電解質中の..
arxiv.org/abs/1404.6177v1
>惑星を持つリチウム貧弱星における..
arxiv.org/abs/astro-ph/0310698v1
>オープンソースソフトウェアを用い..
arxiv.org/abs/1805.03256v1
INFO:_:keywords 大丈夫？ are sent by soraemonpockts
INFO:_:processing translate 15967338917551891220
INFO:_:all:'大丈夫？'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 0 entries
INFO:arxiv.arxiv:No more entries left to fetch.
INFO:arxiv.arxiv:Fetching finished.
INFO:_:no retlist, 大丈夫？
INFO:_:keywords なんかプチパズしそうなので宣伝します！  を作りました！  FFになった後にリプライ(言語不問)を送ると、その内容に関する論文を取ってきて返しま… https://t.co/Jx684gPtE9 are sent by soraemonpockts
INFO:_:processing translate 15967338971292688025
INFO:_:all:'I'm going to advertise it because it's going to be something of a petit puzzler!  I made a!  If you send a reply (in any language) after being FF, I'll get a paper on the subject and return it to you... https://t.co/Jx684gPtE9'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 4 entries
INFO:_:processing translate 15967339116608006486
INFO:_:[auto_follows] started at 2020-08-06 17:11:54.829378
INFO:_:processing translate 15967339156779254416
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "demo.py", line 35, in auto_follows
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "demo.py", line 19, in run
    try: func()
  File "demo.py", line 35, in <lambda>
    run(lambda:bot.auto_follow(), interval, initsleep, funcname)
  File "/home/ubuntu/PaperTranslateBot/src/bot.py", line 25, in auto_follow
    self.twitter.followback()
  File "/home/ubuntu/PaperTranslateBot/src/Twitter.py", line 24, in followback
    for n in new: self.logger.info("new followers", id_dic[n].screen_name)
Message: 'new followers'
Arguments: ('zacuelgt',)
INFO:_:processing translate 15967339286900409612
INFO:_:processing translate 15967339356975148895
INFO:_:processing translate 15967339467089734413
INFO:_:processing translate 15967339527157408034
INFO:_:processing translate 15967339687318499265
INFO:_:processing translate 1596733973737572807
INFO:_:@soraemonpockts :I'm going to advertise it because it'...
>How to Tr..
arxiv.org/abs/1407.0697v1
>量子力学に関する3..
arxiv.org/abs/1809.10725v1
>クラウド市場の経済..
arxiv.org/abs/1103.0045v1
>トップダウンシナリ..
arxiv.org/abs/hep-ph/0403299v2
INFO:_:keywords 筋肉 are sent by A_p_julius
INFO:_:processing translate 15967339949265798433
INFO:_:all:'筋肉'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 0 entries
INFO:arxiv.arxiv:No more entries left to fetch.
INFO:arxiv.arxiv:Fetching finished.
INFO:_:no retlist, 筋肉
INFO:_:keywords 英語弱すぎる are sent by soraemonpockts
INFO:_:processing translate 15967340002022720057
INFO:_:all:'英語弱すぎる'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 0 entries
INFO:arxiv.arxiv:No more entries left to fetch.
INFO:arxiv.arxiv:Fetching finished.
INFO:_:no retlist, 英語弱すぎる
INFO:_:keywords    https://t.co/mnmbxs48KP are sent by HL873163
INFO:_:processing translate 15967340055997382437
INFO:_:all:'   https://t.co/mnmbxs48KP'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 0 entries
INFO:arxiv.arxiv:No more entries left to fetch.
INFO:arxiv.arxiv:Fetching finished.
INFO:_:no retlist,    https://t.co/mnmbxs48KP
INFO:_:[auto_reply] started at 2020-08-06 17:14:56.667484
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:14:58.033198
INFO:_:[auto_reply] started at 2020-08-06 17:17:52.698449
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:17:56.771504
INFO:_:[auto_reply] started at 2020-08-06 17:20:52.521918
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:20:53.174443
INFO:_:[auto_reply] started at 2020-08-06 17:20:54.004044
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:20:57.391005
INFO:_:[auto_reply] started at 2020-08-06 17:20:58.640883
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_reply] started at 2020-08-06 17:23:52.917292
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:23:57.300476
INFO:_:[auto_reply] started at 2020-08-06 17:23:59.417045
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_reply] started at 2020-08-06 17:26:55.059970
INFO:_:keywords  chocolate Thermogravimetric analysis are sent by phosgene_titech
INFO:_:all:' chocolate Thermogravimetric analysis'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:_:[auto_follows] started at 2020-08-06 17:26:56.626595
INFO:arxiv.arxiv:Received 4 entries
INFO:_:processing translate 15967348168527440059
INFO:_:processing translate 15967348248736393649
INFO:_:processing translate 15967348328809385649
INFO:_:processing translate 15967348388878265681
INFO:_:processing translate 15967348559042745621
INFO:_:processing translate 15967348619104553617
INFO:_:processing translate 15967348729220236833
INFO:_:processing translate 15967348789288070475
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
INFO:_:@phosgene_titech 
>チョコレートブルームのラマン分光
arxiv.org/abs/1612.00741v1
>不偏不党のチョコレートバーゲームのグラ..
arxiv.org/abs/1711.05035v1
>不偏不党の三角形のチョコレートバーゲーム
arxiv.org/abs/1711.04954v1
>二酸化スズの構造と電子状態の変化
arxiv.org/abs/1606.08137v1
INFO:_:[auto_reply] started at 2020-08-06 17:29:52.786260
INFO:_:keywords  chocolate thermal gravimetric are sent by phosgene_titech
INFO:_:all:' chocolate thermal gravimetric'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 4 entries
INFO:_:processing translate 15967349943813289681
INFO:_:[auto_follows] started at 2020-08-06 17:29:54.669461
INFO:_:processing translate 15967349994001916838
INFO:_:[auto_follows] started at 2020-08-06 17:29:59.600402
INFO:_:processing translate 15967350174180233645
INFO:_:processing translate 15967350224220617673
INFO:_:processing translate 15967350334329248057
INFO:_:processing translate 15967350384369174471
INFO:_:processing translate 15967350444436224033
INFO:_:processing translate 15967350494493078481
INFO:_:@phosgene_titech 
>不偏不党のチョコレートバーゲームのグラン..
arxiv.org/abs/1711.05035v1
>不偏不党の三角形のチョコレートバーゲーム
arxiv.org/abs/1711.04954v1
>チョコレートブルームのラマン分光
arxiv.org/abs/1612.00741v1
>チョコレートの数字
arxiv.org/abs/1509.06093v1
INFO:_:[auto_follows] started at 2020-08-06 17:32:54.795633
INFO:_:[auto_reply] started at 2020-08-06 17:32:56.912163
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_reply] started at 2020-08-06 17:32:59.490728
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:35:52.155227
INFO:_:[auto_reply] started at 2020-08-06 17:35:54.271849
INFO:_:keywords ferromagnetic are sent by mooupng
INFO:_:all:'ferromagnetic'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 4 entries
INFO:_:processing translate 15967353561165836887
INFO:_:[auto_follows] started at 2020-08-06 17:35:57.400953
INFO:_:processing translate 15967353631370329692
INFO:_:processing translate 15967353691427881642
INFO:_:processing translate 15967353761503628814
INFO:_:processing translate 15967353851602969681
INFO:_:processing translate 15967353911671382444
INFO:_:processing translate 15967354001758422451
INFO:_:processing translate 15967354071837283253
INFO:_:@mooupng 
>電子スピンアレイと強磁性..
arxiv.org/abs/1401.0878v1
>臨界温度付近の強磁性体$..
arxiv.org/abs/cond-mat/0212031v1
>強磁性体/超伝導体/強磁..
arxiv.org/abs/cond-mat/0410351v1
>長岡の強磁性からフラット..
arxiv.org/abs/cond-mat/9712219v3
INFO:_:[auto_reply] started at 2020-08-06 17:38:51.698011
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_reply] started at 2020-08-06 17:38:52.354262
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_reply] started at 2020-08-06 17:38:55.484380
INFO:_:[auto_follows] started at 2020-08-06 17:38:55.531151
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_reply] started at 2020-08-06 17:41:54.407377
INFO:_:[auto_follows] started at 2020-08-06 17:41:54.409711
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_reply] started at 2020-08-06 17:41:54.935606
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:41:55.514842
INFO:_:[auto_reply] started at 2020-08-06 17:41:59.270289
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:44:54.733429
INFO:_:[auto_reply] started at 2020-08-06 17:44:56.366840
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:47:53.359726
INFO:_:[auto_reply] started at 2020-08-06 17:47:55.409603
INFO:_:keywords 関連性理論　分裂分 are sent by teruyan_44
INFO:_:processing translate 15967360760889340899
INFO:_:[auto_follows] started at 2020-08-06 17:47:56.761492
INFO:_:all:'関連性理論　分裂分'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 0 entries
INFO:arxiv.arxiv:No more entries left to fetch.
INFO:arxiv.arxiv:Fetching finished.
INFO:_:no retlist, 関連性理論　分裂分
INFO:_:[auto_reply] started at 2020-08-06 17:50:51.202641
INFO:_:keywords conversational implicature are sent by teruyan_44
INFO:_:all:'conversational implicature'
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:_:[auto_follows] started at 2020-08-06 17:50:52.285826
INFO:arxiv.arxiv:Received 4 entries
INFO:_:processing translate 15967362523388937681
INFO:_:[auto_follows] started at 2020-08-06 17:50:56.618972
INFO:_:processing translate 15967362573534304062
INFO:_:processing translate 15967362673642403292
INFO:_:processing translate 15967362733706211271
INFO:_:processing translate 15967362853835097636
INFO:_:processing translate 15967362913902278436
INFO:_:processing translate 1596736308408482564
INFO:_:processing translate 15967363144147257614
INFO:_:@teruyan_44 
>Rationality, ..
arxiv.org/abs/cmp-lg/9806004v1
>英語対話における会話的含意..
arxiv.org/abs/1911.10704v1
>推論のデフォルトルールによ..
arxiv.org/abs/cmp-lg/9609002v1
>参照表現の生成におけるグリ..
arxiv.org/abs/cmp-lg/9504020v1
INFO:_:[auto_follows] started at 2020-08-06 17:53:53.395311
INFO:_:[auto_follows] started at 2020-08-06 17:53:55.723958
INFO:_:[auto_reply] started at 2020-08-06 17:53:58.561738
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:56:52.788114
INFO:_:[auto_reply] started at 2020-08-06 17:56:53.712258
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:59:52.014285
INFO:_:[auto_reply] started at 2020-08-06 17:59:52.397540
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_reply] started at 2020-08-06 17:59:55.143739
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_tweets] started at 2020-08-06 17:59:56.241672
INFO:_:cat:'math.QA' AND submittedDate:[20191112 TO 20200804235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:arxiv.arxiv:Received 1 entries
INFO:arxiv.arxiv:... play nice on the arXiv and sleep a bit ...
INFO:_:[auto_reply] started at 2020-08-06 17:59:57.421678
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 17:59:59.047358
INFO:arxiv.arxiv:Fetch from arxiv (4 results left to download)
INFO:arxiv.arxiv:Received 4 entries
INFO:_:cat:'math.QA' AND submittedDate:[20190719 TO 20200804235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:arxiv.arxiv:Received 5 entries
INFO:_:cat:'math.QA' AND submittedDate:[20191005 TO 20200804235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:arxiv.arxiv:Received 5 entries
INFO:_:cat:'math.QA' AND submittedDate:[20181107 TO 20200804235959]
INFO:arxiv.arxiv:Start downloading
INFO:arxiv.arxiv:Fetch from arxiv (5 results left to download)
INFO:arxiv.arxiv:Received 5 entries
INFO:_:processing translate 15967368025727744082
INFO:_:processing translate 15967368096242611221
INFO:_:processing translate 15967368206351712025
INFO:_:processing translate 15967368276430982445
INFO:_:processing translate 15967368376534012871
INFO:_:processing translate 1596736843660220802
INFO:_:processing translate 15967368526689254463
INFO:_:processing translate 15967368586758070427
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
Loading page (1/2)
[>                                                           ] 0%[==============================>                             ] 50%[============================================================] 100%Rendering (2/2)                                                    
[>                                                           ] 0%[===============>                                            ] 25%[============================================================] 100%Done                                                               
INFO:_:[auto_reply] started at 2020-08-06 18:02:54.890293
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 18:02:58.390173
INFO:_:[auto_reply] started at 2020-08-06 18:02:59.656737
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_reply] started at 2020-08-06 18:05:52.883172
INFO:_:reply tweets doesn't exist.
INFO:_:[auto_follows] started at 2020-08-06 18:05:56.666346
INFO:_:[auto_reply] started at 2020-08-06 18:05:59.732891
INFO:_:reply tweets doesn't exist.
